---
- uid: 'dgfip/chiffres_affaires'
  path: '/v3/dgfip/etablissements/{siret}/chiffres_affaires'
  position: 210
  perimeter:
    entity_type_description: "Seuls les chiffres d&apos;affaires des **entreprises qui vérifient les deux conditions** suivantes, sont disponibles:
    \n
    \n
    - ✅ être **soumises à l&apos;impôt sur les sociétés** selon les règles des régimes d&apos;imposition réels, normal ou simplifié ;
    \n
    - ✅ avoir **transmis ses comptes annuels** aux greffes.
    \n
    \n
    ❌ Les micro-entrepreneurs ne sont pas soumis à l&apos;IS mais à l&apos;IR ; leurs chiffres d&apos;affaires ne sont donc pas disponibles via API Entreprise."
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'dgfip'
  data:
    description: "Cette API retourne uniquement les trois derniers exercices.
    \n
    Ceux-ci ne sont pas forcément les exercices des trois dernières années car il peut y avoir plusieurs exercices dans une même année. Le nombre d’exercices renvoyés varie de 1 à 3.
    Les exercices renvoyés sont listés les uns après les autres, le premier étant le plus récent des trois.
    \n
    \n
    Pour chaque exercice, le chiffre d’affaire en euros et la date de fin de l’exercice sont transmis."
  opening: protected
  use_cases:
    - Aides publiques
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: "Quelle est la définition du chiffre d&apos;affaires transmis ?"
      a: "**En régime réel normal**, le chiffres d&apos;affaire correspond au montant porté en case FL du
[formulaire 2052 - compte de résultat de l&apos;exercice](https://www.impots.gouv.fr/portail/files/formulaires/2052-sd/2018/2052-sd_2117.pdf}{:target=\"_blank\"}),
c&apos;est-à-dire, le total des chiffres d&apos;affaire nets de France et d&apos;exportations et livraisons intracommunautaires.
      \n
      \n
      **En régime réel simplifié**, le chiffre d&apos;affaires correspond à la somme des montants indiqués dans les cases 210, 214 et 218 du
[formulaire 2033B - compte de résultat simplifié de l&apos;exercice](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2018/2033-sd_2094.pdf}{:target=\"_blank\"}),
c&apos;est-à-dire le total&nbsp;:
      \n
      \n
      - des ventes de marchandises (dont export et livraisons intracommunautaires) ;
      \n
      - de la production vendue des biens ;
      \n
      - de la production vendue des services, c&apos;est-à-dire &laquo;&nbsp;*du montant des travaux, études et
prestations de services exécutés, comprenant le cas échéant les produits des activités annexes
(services exploités dans l&apos;intérêt du personnel, commissions et courtages, locations diverses,
mises à disposition de personnel facturées, ports et frais accessoires facturés, boni sur remises
d&apos;emballages consignés).*&nbsp;&raquo;
      \n
      \n
      [**Source : impôts.gouv**](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2019/2033-sd_2570.pdf}{:target=\"_blank\"})"
