---
- uid: 'dgfip/chiffres_affaires'
  path: '/v3/dgfip/chiffres_affaires/{siret}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Seuls les trois derniers exercices sont renvoyés.
    \n
    Ceux-ci ne sont pas forcément les exercices des trois dernières années car il peut y avoir plusieurs exercices dans une même année. Le nombre d’exercices renvoyés varie de 1 à 3.
    Les exercices renvoyés sont listés les uns après les autres, le premier étant le plus récent. 
    \n
    \n
    Pour chaque exercice, le chiffre d’affaire en euros et la date de fin de l’exercice sont transmis.
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    Sont disponibles uniquement les chiffres d'affaires des **entreprises qui
    vérifient les deux conditions** suivantes&nbps;:
    \n
    \n
    - ✅ être **soumises à l'impôt sur les sociétés** selon les règles des régimes d'imposition réels, normal ou simplifié ;
    \n
    - ✅ avoir **transmis ses comptes annuels** aux greffes.
    \n
    \n
    Les micro-entrepreneurs ne sont pas soumis à l'IS mais à l'IR ; leurs chiffres d'affaires ne sont donc pas disponibles via API Entreprise.
    \n
    \n
    entities:
      - entreprises
  call_id: "SIRET"
  providers:
    - 'dgfip'
  opening: protected
  use_cases:
    - Aides publiques
    - Marchés publics
  parameters:
    - Numéro de SIRET de l'établissement
  faq:  
    - q: "Quelle est la définition du chiffre d'affaires transmis ?"
      a: "
      ###### Le cas du régime réel normal
      \n
      \n
      Le chiffre d'affaire correspond au montant porté en case FL du 
[formulaire 2052 - compte de résultat de l'exercice](https://www.impots.gouv.fr/portail/files/formulaires/2052-sd/2018/2052-sd_2117.pdf}{:target="_blank"}), 
c'est-à-dire, le total des chiffres d'affaire nets de France et d'exportations et livraisons intracommunautaires.
      \n
      \n
      ###### Le cas du régime réel simplifié
      \n
      \n
      Le chiffre d'affaire correspond à la somme des montants indiqués dans les cases 210, 214 et 218 du 
      [formulaire 2033B - compte de résultat simplifié de l'exercice](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2018/2033-sd_2094.pdf}{:target="_blank"}),
      c'est à dire le total&nbsp;:
      \n
      \n
      - des ventes de marchandises (dont export et livraisons intracommunautaires) ;
      \n
      - de la production vendue des biens ;
      \n
      - de la production vendue des services, c'est à dire &laquo;*du montant des travaux, études et 
prestations de services exécutés, comprenant le cas échéant les produits des activités annexes 
(services exploités dans l'intérêt du personnel, commissions et courtages, locations diverses, 
mises à disposition de personnel facturées, ports et frais accessoires facturés, boni sur remises 
d'emballages consignés).*&raquo;
      \n
      \n
      [**Source : impôts.gouv**](https://www.impots.gouv.fr/portail/files/formulaires/2033-sd/2019/2033-sd_2570.pdf}{:target="_blank"})"
