---
- uid: 'dgfip/liasses_fiscales'
  path: '/v3/dgfip/liasses_fiscales/declarations/{year}/{siren}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Cette API délivre la liste des différentes conventions de l’établissement.
    Les caractéristiques suivantes sont données&nbsp;:
    \n
    \n
    - le titre et le titre court de la convention ;
    \n
    - l’état en vigueur étendu ou non de la convention ;
    \n
    - son identifiant IDCC, numéro à 4 chiffres ;
    \n
    - l’URL Légifrance du texte en vigueur.
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    Cette API délivre les liasses fiscales des entreprises&nbsp;:
    \n
    - ✅ soumises à l’impôt sur les sociétés (IS)* ;
    \n
    - ✅ soumises à l’impôt sur les sociétés dû par le groupe (IS GROUPE)*;
    \n
    - ✅ aux bénéfices industriels et commerciaux (BIC)* ;
    \n
    - ✅ aux bénéfices non commerciaux (BNC)* ;
    \n
    - ✅ aux bénéfices agricoles (BA)*.
    \n
    \n
    *selon les règles des régimes réels normal ou simplifié.
    \n
    \n
    ℹ️ Les entreprises anciennement aux forfaits BIC/BNC/BA , désormais ❌ régimes micro-BIC, micro-BNC 
et micro-BA ne déposent pas de déclaration de résultat mais des éléments spécifiques dans la déclaration 2042C
 qui relève de d’impôt sur le revenu et ne sont donc pas dans le périmètre de cet endpoint.
    \n
    \n
    **Fraicheur de la donnée&nbsp;:**
    \n
    \n
    Les déclarations de résultat sont disponibles à compter du lendemain de la date de dépôt (J+1) 
et trois jours plus tard (J+3) si le dépôt intervient une veille de week-end.
    \n
    \n
    La date limite de dépôt des déclarations de résultat est fixée au 2ème jour ouvré qui suit le 1er mai pour les entreprises 
qui clôturent à la fin de l’année civile.
    \n
    \n
    En cas d’exercice à cheval, la date limite de dépôt est positionnée exactement 3 mois après la date de clôture de l’exercice déclaré."
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'dgfip'
  opening: protected
  use_cases:
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l&apos;entreprise
  faq:  
    - q: "Comment distinguer l&apos;imprimé rectificatif de l&apos;initial ?"
      a: "Il peut arriver que pour un même exercice il y ait plusieurs fois le même imprimé&nbps;; 
il s&apos;agit de corrections qui ont été apportées par une déclaration ultérieure.
      \n
      \n
      Les déclarations dans le JSON sont triées de l&apos;imprimé le plus récent au plus ancien.
      \n
      Ainsi **le premier imprimé est toujours le plus récent**.
      \n
      \n
      Par ailleurs, les deux imprimés auront toujours la même `date_declaration` qui correspond 
à la date du correctif. Celle-ci ne vous permet donc pas de distinguer l&apos;imprimé rectificatif de 
l&apos;imprimé initial, pour lequel il n&apos;est pas possible de connaître la date de déclaration."
