---
- uid: 'msa/conformites_cotisations'
  path: '/v3/msa/etablissements/{siret}/conformite_cotisations'
  position: 270
  perimeter:
    entity_type_description: "Sont éligibles à la MSA les entreprises de&nbsp;:
    \n
    - l&apos;agriculture ;
    \n
    - l&apos;élevage ;
    \n
    - la pèche ;
    \n
    - le forestier."
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  providers:
    - 'msa'
  data:
    description: "Cette API indique si l&apos;entreprise est à jour de ses cotisations sociales auprès de la MSA. Il existe donc trois situations possibles pour une entreprise&nbsp;:
    \n
    \n
    - L&apos;entreprise est à jour de ses cotisations sociales auprès de la MSA ;
    \n
    - L&apos;entreprise n’est pas à jour de ses cotisations sociales ;
    \n
    - La régularité de l&apos;entreprise est inconnue. Une analyse est à effectuer par un agent caisse de la MSA pour savoir si le débiteur est à jour ou pas.
Ce cas particulier intervient sur un laps de temps limité.
    \n
    \n
    {:.fr-highlight}
    ℹ️ Depuis 2021, la conformité n&apos;est délivrée que si la contribution annuelle de l&apos;OETH (Obligation d’Emploi de Travailleur Handicapé)
a été acquittée par l&apos;entreprise. Cette compétence était auparavant attribuée à l&apos;AGEFIPH."
  opening: protected
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
