---
- uid: 'msa/conformites_cotisations'
  path: '/v3/msa/conformites_cotisations/{siret}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    La réponse indique si l’entreprise est à jour de ses cotisations sociales auprès de la MSA.
    Il existe donc 3 situations possibles pour une entreprise&nbps;:
    \n
    \n
    - L’entreprise est à jour de ses cotisations sociales auprès de la MSA ;
    \n
    L’entreprise n’est pas à jour de ses cotisations sociales ;
    \n
    La régularité de l’entreprise est inconnue. Une analyse est à effectuer par un agent caisse de la MSA pour savoir si le débiteur est à jour ou pas. 
Ce cas particulier intervient sur un laps de temps limité.
    \n
    \n
    ℹ️ Depuis 2021, la conformité n’est délivrée que si la contribution annuelle de l’OETH (Obligation d’Emploi de Travailleur Handicapé) 
a été acquittée par l’entreprise. Cette compétence était auparavant attribuée à l’AGEFIPH.
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    Sont éligibles à la MSA les entreprises de :
    \n
    - l’agriculture ;
    \n
    - l’élevage ;
    \n
    - la pèche ;
    \n
    - le forestier.
    \n
    \n"
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  providers:
    - 'msa'
  opening: protected
  use_cases:
    - Aides publiques
    - Marchés publics
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
