---
- uid: 'msa/conformites_cotisations'
  path: '/v3/msa/etablissements/{siret}/conformite_cotisations'
  position: 270
  perimeter:
    entity_type_description: |+
      Sont éligibles à la MSA les entreprises de&nbsp;:
      - l'agriculture ;
      - l'élevage ;
      - la pèche ;
      - le forestier.
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  providers:
    - 'msa'
  data:
    description: |+
      Cette API indique si l'entreprise est à jour de ses cotisations sociales auprès de la MSA. Il existe donc trois situations possibles pour une entreprise :
      - L'entreprise est à jour de ses cotisations sociales auprès de la MSA ;
      - L'entreprise n’est pas à jour de ses cotisations sociales ;
      - La régularité de l'entreprise est inconnue. Une analyse est à effectuer par un agent caisse de la MSA pour savoir si le débiteur est à jour ou pas.
        Ce cas particulier intervient sur un laps de temps limité.


      {:.fr-highlight}
      ℹ️ Depuis 2021, la conformité n'est délivrée que si la contribution annuelle de l'OETH (Obligation d’Emploi de Travailleur Handicapé) a été acquittée par l'entreprise. Cette compétence était auparavant attribuée à l'AGEFIPH.

  opening: protected
  use_cases:
    - Marchés publics
    - Aides publiques
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
