---
- uid: 'probtp/conformites_cotisations_retraite'
  path: '/v3/probtp/attestations_cotisations_retraite/{siret}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    TODO
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    TODO
    \n
    \n
    **Fraicheur de la donnée&nbsp;:**
    \n
    \n
    TODO
    \n
    \n"
    entities:
      - entreprises
  call_id: "SIRET"
  providers:
    - 'probtp'
  opening: protected
  use_cases:
    - Aides publiques
    - Marchés publics
    - Détection de la fraude
  parameters:
    - Numéro de SIRET de l'établissement
