---
- uid: 'fntp/carte_professionnelle_travaux_public'
  path: '/v3/fntp/cartes_professionnelle_travaux_publics/{siren}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Cette API délivre la carte professionnelle de travaux publics d&apos;une entreprise
lorsque cette dernière est en règle de ses obligations sociales, administratives et juridiques.
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    Toutes les entreprises de travaux publics sont éligibles à demander une carte professionnelle à la FNTP.
    Au mois d&apos;avril 2022, 7400 entreprises possédaient une carte professionnelle.
    \n
    \n
    ℹ️ Plus d&apos;informations sur le [site de la FNTP](https://www.fntp.fr/outils/carte-professionnelle/tout-savoir-sur-la-carte-pro}{:target=\"_blank\"})"
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'fntp'
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIREN de l&apos;entreprise
