---
- uid: 'insee/unites_legales'
  path: '/v3/insee/sirene/unites_legales/{siren}'
  position: 105
  perimeter:
    description: "###### Type de données&nbsp;:
    \n
    \n
    Cette API délivre les informations de référence des unités légales inscrites au répertoire Sirene, diffusibles ou \"non-diffusibles\".
    \n
    ⚠️ Elle ne concerne pas&nbsp;:
    \n
    * les établissements, appelables avec les API `sirene/etablissements` et `sirene/etablissements/diffusibles`;
    \n
    * l&apos;adresse des établissements de l&apos;unité légale, appelables avec les API `/sirene/etablissements/:siret/adresse` et `/sirene/etablissements/diffusibles/:siret/adresse` ;
    \n
    * les mandataires sociaux, appelables avec l&apos;API `infogreffe/mandataires_sociaux`.
    \n
    * les informations détaillées du siège social, appelables avec les API `unites_legales/diffusibles/:siren/siege_social` et `unites_legales/:siren/siege_social`.
    \n
    \n
    ###### Entreprises/associations concernées&nbsp;:
    \n
    \n
    Toutes les unités légales suivantes sont présentes&nbsp;:
    \n
    * ✅ les personnes morales de droit privé : les entreprises. Toutes les entreprises immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
    \n
    * ✅ les personnes morales de droit public : les institutions et services de l&apos;État et les collectivités territoriales ;
    \n
    * ✅ les entrepreneurs individuels exerçant de manière indépendante une profession non salariée (exemple : un commerçant, un médecin), ayant fait une déclaration d&apos;activité.
    \n
    * ❌ Les particuliers employeurs ne font pas partie de la base Sirene ;
    \n
    * ✅ les associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu&apos;elles :
    \n
    \t* emploient du personnel salarié ;
    \n
    \t* sont soumises à la TVA ;
    \n
    \t* ont demandé ou bénéficient de transferts financiers publics.
    \n
    * ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
    \n
    \n
    ###### Périmètre géographique&nbsp;:
    \n
    \n
    La base Sirene concerne les unités implantées en métropole, dans les DOM et dans les collectivités d&apos;Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.
    \n
    \n
    ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l&apos;État ou des communes est répertorié ; ❌ les entreprises ne sont donc pas disponibles.
    \n
    \n
    ###### Fraicheur de la donnée&nbsp;:
    \n
    \n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l&apos;INSEE.<br>
    \n
    \n
    ###### Pour en savoir plus&nbsp;:
    \n
    \n
    [Contexte juridique du Répertoire National d&apos;identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - entreprises_diffusibles
    - associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIREN
  parameters: &insee_unites_legales_parameters
    - Numéro de SIREN de l'unité légale
  use_cases: &insee_unites_legales_use_cases
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
    - Détection de la fraude
  providers: &insee_unites_legales_providers
    - 'insee'
  faq:  
    - q: "Qu&apos;est-ce que l&apos;état administratif d&apos;une entité légale ?"
      a: "L&apos;état administratif indique si une unité légale est active ou cessée.
      \n
      \n
      **Pour les personnes morales**, l&apos;unité légale est considérée comme juridiquement cessée si :
      \n
      \n
      - il y a eu dépôt de la déclaration de disparition de la personne morale ;
      \n
      - elle a été inscrite sans activité à sa demande. Dans le cas d&apos;une création au répertoire Sirene mais sans avoir encore démarré une activité (activité principale provisoire “0000Z”) ;
      \n
      - elle n&apos;a plus d&apos;établissement en activité.
      \n
      \n
      **Pour les personnes physiques**, l&apos;unité légale est considérée comme juridiquement cessée si :
      \n
      - l&apos;exploitant de l&apos;unité légale décède ;
      \n
      - l&apos;exploitant dépose une cessation d&apos;activité.
      \n
      \n
      En dehors de ces cas, l&apos;état administratif de l&apos;unité légale est toujours \"actif\"."
    - q: "Une unité légale sembe être successivement active puis cessée puis active, est&#8209;ce normal ?"
      a: "**Pour les personnes physiques**, dans le cas où l&apos;exploitant déclare la cessation de son activité, 
      puis la reprend quelque temps plus tard, **l&apos;état administratif est réversible**. Il est donc normal d&apos;avoir des périodes successives 
      d&apos;état actif puis cessé pour les personnes physiques.
      \n
      \n
      En revanche, **pour les personnes morales, l&apos;état administratif est en théorie irréversible**."
    - q: "Une unité légale est active mais tous ses établissements sont fermés, est&#8209;ce une erreur ?"
      a: "Même si tous les établissements d&apos;une unité légale sont fermés, y compris son établissement siège, 
      **une unité légale reste active tant que la cessation juridique n&apos;a pas été prononcée. 
      Une réactivation est même encore possible. Le SIREN continue donc d&apos;avoir un statut \"actif\" au répertoire."
    - q: "Qu&apos;est&#8209;ce qu&apos;un \"non-diffusible\" ?"
      a: "Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement
      des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion commerciale, 
      en vertu de l&apos;[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/). 
      \n
      Cela signifie qu&apos;elles donnent accord de la diffusion de leur données uniquement à des organismes habilités 
      et à des administrations. **De fait, leurs données ne sont pas publiques**.
      \n
      \n
      ℹ️ Les unités de la Défense nationale font également partie des \"non-diffusibles\" mais ne sont accessibles 
      que sur autorisation du Ministère de la Défense, conformément à l&apos;[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/)."
    - q: "Comment utiliser les informations des unités légales \"non-diffusibles\" ?"
      a: "En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l&apos;entité appelée. 
      Dans le cas où l&apos;entité est indiquée comme \"non-diffusible\", vous vous engagez à n&apos;utiliser leurs informations que dans le cadre strict 
      de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.
      \n
      \n
      {:.fr-highlight--caution}
      > ⚠️ **Vous ne pouvez pas donc pas faire usage des données d'une entité \"non-diffusible\ pour du pré-remplissage.** 
      {:.fr-highlight}
      > Il vous est par contre possible d'indiquer à l'unité légale \"non-diffusible\ qu&apos;elle peut modifier son statut, même provisoirement, auprès de l&apos;Insee à l&apos;adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr}{:target=\"_blank\"})."
- uid: 'insee/unites_legales_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}'
  position: 100
  perimeter:
    description: "####### Type de données&nbsp;:
    \n
    \n
    Cette API délivre les informations de référence concernant les unités légales inscrites au répertoire Sirene et diffusibles commercialement.
    \n
    ⚠️ Elle ne concerne pas&nbsp;:
    \n
    * les unités légales non diffusibles, appelables avec l&apos;API `sirene/unites_legales/diffusibles` ;
    \n
    * les établissements, appelables avec les API `sirene/etablissements` et `sirene/etablissements/diffusibles`;
    \n
    * l&apos;adresse des établissements de l&apos;unité légale, appelables avec les API `/sirene/etablissements/:siret/adresse` et `/sirene/etablissements/diffusibles/:siret/adresse` ;
    \n
    * les mandataires sociaux, appelables avec l&apos;API `infogreffe/mandataires_sociaux`.
    \n
    * les informations détaillées du siège social, appelables avec les API `unites_legales/diffusibles/:siren/siege_social` et `unites_legales/:siren/siege_social`.
    \n
    \n
    ###### Entreprises/associations concernées&nbsp;:
    \n
    \n
    * Uniquement les unités dîtes \"diffusibles\", c&apos;est-à-dire ayant donné leur accord pour que leurs informations soient publiques et utilisées à des fins commerciales.
    \n
    * ✅ les personnes morales de droit privé : les entreprises. Toutes les entreprises immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
    \n
    * ✅ les personnes morales de droit public : les institutions et services de l&apos;État et les collectivités territoriales ;
    \n
    * ✅ les entrepreneurs individuels exerçant de manière indépendante une profession non salariée (exemple : un commerçant, un médecin), ayant fait une déclaration d'activité.
    \n
    * ❌ Les particuliers employeurs ne font pas partie de la base Sirene ;
    \n
    * ✅ les associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu&apos;elles :
    \n
    \t* emploient du personnel salarié ;
    \n
    \t* sont soumises à la TVA ;
    \n
    \t* ont demandé ou bénéficient de transferts financiers publics.
    \n
    * ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
    \n
    \n
    ###### Périmètre géographique&nbsp;:
    \n
    \n
    La base Sirene concerne les unités implantées en métropole, dans les DOM et dans les collectivités d&apos;Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.
    \n
    \n
    ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l&apos;État ou des communes est répertorié ; ❌ les entreprises ne sont donc pas disponibles.
    \n
    \n
    ###### Fraicheur de la donnée&nbsp;:
    \n
    \n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l&apos;INSEE.<br>
    \n
    \n
    ###### Pour en savoir plus&nbsp;:
    \n
    \n
    [Contexte juridique du Répertoire National d&apos;identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - entreprises
    - associations
  opening: public
  use_cases: *insee_unites_legales_use_cases
  parameters: *insee_unites_legales_parameters
  call_id: *insee_unites_legales_call_id
  providers: *insee_unites_legales_providers
  faq:  
    - q: "Qu&apos;est-ce que l&apos;état administratif d&apos;une entité légale ?"
      a: "L&apos;état administratif indique si une unité légale est active ou cessée.
      \n
      \n
      **Pour les personnes morales**, l&apos;unité légale est considérée comme juridiquement cessée si :
      \n
      \n
      - il y a eu dépôt de la déclaration de disparition de la personne morale ;
      \n
      - elle a été inscrite sans activité à sa demande. Dans le cas d&apos;une création au répertoire Sirene mais sans avoir encore démarré une activité (activité principale provisoire “0000Z”) ;
      \n
      - elle n&apos;a plus d&apos;établissement en activité.
      \n
      \n
      **Pour les personnes physiques**, l&apos;unité légale est considérée comme juridiquement cessée si :
      \n
      - l&apos;exploitant de l&apos;unité légale décède ;
      \n
      - l&apos;exploitant dépose une cessation d&apos;activité.
      \n
      \n
      En dehors de ces cas, l&apos;état administratif de l&apos;unité légale est toujours \"actif\"."
    - q: "Une unité légale sembe être successivement active puis cessée puis active, est&#8209;ce normal ?"
      a: "**Pour les personnes physiques**, dans le cas où l&apos;exploitant déclare la cessation de son activité, 
      puis la reprend quelque temps plus tard, **l&apos;état administratif est réversible**. Il est donc normal d&apos;avoir des périodes successives 
      d&apos;état actif puis cessé pour les personnes physiques.
      \n
      \n
      En revanche, **pour les personnes morales, l&apos;état administratif est en théorie irréversible**."
    - q: "Une unité légale est active mais tous ses établissements sont fermés, est&#8209;ce une erreur ?"
      a: "Même si tous les établissements d&apos;une unité légale sont fermés, y compris son établissement siège, 
      **une unité légale reste active tant que la cessation juridique n&apos;a pas été prononcée. 
      Une réactivation est même encore possible. Le SIREN continue donc d&apos;avoir un statut \"actif\" au répertoire."
