---
- uid: 'qualibat/certifications_batiment'
  path: '/v3/qualibat/certifications_batiment/{siret}'
  position: 330
  perimeter:
    entity_type_description: "Toutes les entreprises et les artisans du bâtiment ayant obtenu le label de fiabilité Qualibat."
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  providers:
    - 'qualibat'
  data:
    description: "Cette API délivre le certificat Qualibat de l&apos;entreprise au format PDF, comportant de nombreuses informations.
    \n
    \n
    **Des informations sur l&apos;établissement&nbsp;:**
    \n
    \n
    - raison sociale, date de création, forme juridique, code NACE et capital social ; 
    \n
    - adresse et coordonnées de l@apos;entreprise ;
    \n
    - nom et fonction des dirigeants responsables ;
    \n
    - registre de commerce ou de répertoire des métiers auquel l&apos;entreprise est rattachée ;
    \n
    - numéro d&apos;affiliation à la caisse de congés payés ;
    \n
    - régularité de la situation fiscale et sociale ;
    \n
    - assurances responsabilité civile et travaux ;
    \n
    - effectif moyen et chiffre d&apos;affaires hors taxes.
    \n
    \n
    **Des informations sur la qualification&nbsp;:**
    \n
    \n
    - code à quatre chiffres de la capacité technique reconnue à l&apos;entreprise dans une des 9 activités détaillées sur le [site Qualibat](https://www.qualibat.com/nomenclature/}{:target=\"_blank\"});
    \n
    - titre de cette capacité ;
    \n
    - niveau de technicité ;
    \n
    - classification partielle : les moyens humains dont dispose l&apos;entreprise dans l&apos;activité pour laquelle elle est qualifiée sont précisés.
    \n
    - date d&apos;attribution : date à laquelle la qualification a été attribuée ou dernièrement renouvellée ;
    \n
    - date d&apos;échéance : date d&apos;expiration de validité de la qualification ;
    \n
    - système qualité : dans la mesure où l&apos;entreprise a mis en place une démarche qualité certifiée par QUALIBAT,
    la certification de son système qualité est mentionnée en annexe.
    \n
    \n
    **Des informations liées au certificat&nbsp;:**
    \n
    \n
    - millésime ;
    \n
    - durée de validité ;
    \n
    - numéro d&apos;identification du certificat.
    \n
    \n
    [**Source&nbsp;: Qualibat**](https://www.qualibat.com/){:target=\"_blank\"})"
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIRET de l'établissement
