---
- uid: 'inpi/brevets'
  path: '/v3/inpi/unites_legales/{siren}/brevets'
  position: 350
  perimeter:
    entity_type_description: |+
      Cette API délivre ✅ uniquement les brevets pour lesquels un SIREN était précisé par l'entreprise lors du dépôt. L'INPI indique qu'environ 80% des demandes de brevets publiées ces vingt dernières années sont rattachées à un SIREN.
    geographical_scope_description: |+
      ✅ Les brevets France et Europe sont disponibles.
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  providers:
    - 'inpi'
  data:
    description: |+
      Cette API délivre :
      - le **nombre de brevets déposés** par l'entreprise, pour lesquels le SIREN était précisé dans le dépôt.
      - Une **liste des derniers brevets** déposés est également renvoyée, et permet d'obtenir les informations suivantes :
        * le titre du brevet ;
        * le numéro du brevet et le code de la zone géographique liés à l'organisation où le brevet a été déposé ;
        * le code de la catégorie du brevet ;
        * les dates de dépôt et de publication.
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'unité légale
