---
- uid: 'inpi/marques'
  path: '/v3/inpi/marques/{siren}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Cette API délivre le nombre de marques déposées par l'entreprise, et pour lesquelles le SIREN était précisé. 
L'INPI indique qu'environ 60% des dépôts de marques France effectués sont rattachés à un SIREN. 
Les marques déposées au niveau européen ou international ne sont pas renvoyées par cette API car le taux de sirenage de ces dépôts est de 0%.
    \n
    \n
    Une liste des dernières marques déposée est également renvoyée, et permet d'obtenir les informations suivantes&nbsp;:
    \n
    \n
    - le nom de la marque ;
    \n
    - le statut du dépôt et de la marque (Demande déposée, publiée, non publiée, totalement rejetée ou irrecevable après publication ; Marque enregistrée, renouvelée, ayant fait l'objet d'une renonciation totale, ayant fait l'objet d'un retrait total, annulée ou expirée ; Renouvellement demandé) ;
    \n
    - le nom du déposant ou du titulaire ; 
    \n
    - la clef associée au dépôt."
    entities:
      - associations
      - entreprises
  # Texte libre
  call_id: "SIREN"
  providers:
    - 'inpi'
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'unité légale
