---
- uid: 'inpi/modeles'
  path: '/v3/inpi/modeles/{siren}'
  position: 370
  perimeter:
    entity_type_description: "Seuls les dessins & modèles déposés par l&apos;entreprise, pour lesquels un SIREN était précisé lors du dépôt. 
L&apos;INPI indique qu&apos;environ 50% des dépôts de dessins & modèles France effectués sont rattachés à un SIREN."
    geographical_scope_description: "Seuls les modèles déposés au niveau français sont disponibles. 
Les modèles déposés au niveau international, à l&apos;OMPI, ne sont pas renvoyés par cette API car le taux de sirenage est de 0%."
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  providers:
    - 'inpi'
  data:
    description: "Cette API délivre&nbsp;:
    \n
    \n
    - le **nombre de modèles déposés** par l&apos;entreprise, pour lesquels le SIREN était précisé lors du dépôt.
    \n
    - Une **liste des derniers modèles déposés** est également renvoyée, et permet d&apos;obtenir, entre autres, les informations suivantes&nbsp;:
    \n
    \t* le titre du modèle et le numéro national sous lequel le modèle est enregistré ;
    \n
    \t* la date de dépôt et la date de publication ;
    \n
    \t* le nom de l&apos;entité ayant déposé le modèle ; 
    \n
    \t* le nombre de vues du modèle."
  opening: public
  use_cases:
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'unité légale
