---
- uid: 'dgfip/attestations_fiscales'
  position: 210
  path: '/v3/dgfip/attestations_fiscales/{siren}'
  perimeter:
    description: "
    
    **Entreprises concernées :**
    \n
    \n
    Cette API ne concerne pas **❌ les sociétés "filles" appartenant à un groupe de société**.
    \n
    ⚠️ Une attestation pourrait toutefois être renvoyée si vous utilisez le SIREN d'une entreprise "fille". Cette attestation ne sera pas valable car incomplète ; en effet, il manquera les informations concernant la société "mère".
    Il est de votre ressort de vérifier si l'entreprise appartient à un groupe IS (défini à l'[article 223 A du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042340402/)) ou TVA (défini à l'[article 1693 ter du CGI](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000030061787/))
    afin de ne pas utiliser une attestation qui ne serait pas valable. Deux API spécifiques à ces sociétés seront bientôt disponibles.
    \n
    \n
    L'attestation de régularité fiscale est **limitée aux ✅ entreprises soumises
    à l'impôt sur les sociétés (IS)**, à l'exclusion des :
    \n
    \n
    * ❌ bénéfices industriels et commerciaux (BIC) ;
    \n
    * ❌ bénéfices non commerciaux (BNC) ;
    \n
    * ❌ bénéfices agricoles (BA) ;
    \n
    \n
    Sont aussi exclues, les :
    \n
    \n
    * ❌ entreprises individuelles ;
    \n
    * ❌ sociétés de personnes ;
    \n
    * ❌ groupements passibles de l'impôt sur le revenu (entrepreneurs individuels).
    \n
    \n
    **Conditions de délivrance de l'attestation :**
    \n
    \n
    L'attestation est délivrée si les obligations déclaratives et de paiement d'IS et de TVA de la société sont en règle. 
    Ainsi, les sociétés bénéficiant d’un plan de règlement, redressement, sauvegarde ou conciliation ainsi que les sociétés ayant formulé un recours contentieux assorti d’un sursis de paiement ne peuvent pas se voir délivrer une attestation fiscale."
    entities:
      - entreprises
  call_id: "SIREN"
  opening: protected
  providers:
    - 'dgfip'
  use_cases:
    - Aides publiques
    - Marchés publics
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de la personne morale recherchée
