---
- uid: 'dgfip/attestations_fiscales'
  position: 210
  path: '/v3/dgfip/attestations_fiscales/{siren}'
  perimeter:
    description: "
    **Entreprises concernées :**
    \n
    \n
    L'attestation de régularité fiscale est **limitée aux ✅ entreprises soumises
    à l'impôt sur les sociétés (IS)**, à l'exclusion des :
    \n
    \n
    * ❌ bénéfices industriels et commerciaux (BIC) ;
    \n
    * ❌ bénéfices non commerciaux (BNC) ;
    \n
    * ❌ bénéfices agricoles (BA) ;
    \n
    \n
    Sont aussi exclues, les :
    \n
    \n
    * ❌ entreprises individuelles ;
    \n
    * ❌ sociétés de personnes ;
    \n
    * ❌ groupements passibles de l'impôt sur le revenu (entrepreneurs individuels).
    \n
    \n
    ⚠️ Cette API ne concerne pas les entreprises appartenant à un groupe de sociétés
    imposé : 
    \n
    \n
    * selon le régime fiscal d'intégration (article 223 A du CGI), dit groupe IS, une API dédiée sera bientôt disponible ;
    \n
    * ou selon un groupe de sociétés ayant opté pour la consolidation du paiement de la TVA
  (article 1693 ter du CGI), dit groupe TVA, une API dédiée sera bientôt disponible.
    \n
    \n
    **Conditions de délivrance de l'attestation :**
    \n
    \n
    L'attestation est délivrée si les obligations déclaratives et de paiement d'IS et de TVA de la société sont en règle. 
    Ainsi, les sociétés bénéficiant d’un plan de règlement, redressement, sauvegarde ou conciliation ainsi que les sociétés ayant formulé un recours contentieux assorti d’un sursis de paiement ne peuvent pas se voir délivrer une attestation fiscale."
    entities:
      - entreprises
  call_id: "SIREN"
  opening: protected
  providers:
    - 'dgfip'
  use_cases:
    - Aides publiques
    - Marchés publics
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de la personne morale recherchée
