---
- uid: 'infogreffe/mandataires_sociaux'
  path: '/v3/infogreffe/mandataires_sociaux/{siren}'
  position: 301
  perimeter:
    description: "Toutes les entreprises inscrites au registre du commerce et des sociétés (RCS) sont concernées. Il s'agit de toutes les entreprises ayant une activité commerciale, plus d'informations sur [le site du ministère de l'économie](https://www.economie.gouv.fr/entreprises/registre-commerce-societes-rcs)"
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'infogreffe'
  opening: protected
  use_cases:
    - Aides publiques
    - Marchés publics
  parameters:
    - Numéro de SIREN de l'entreprise recherchée
