---
- uid: 'insee/adresse_etablissements'
  position: 145
  path: '/v3/insee/sirene/etablissements/{siret}/adresse'
  perimeter:
    description: "###### Type de données&nbsp;:
    \n
    \n
    Cette API délivre l&apos;adresse d&apos;un établissement, diffusible ou non-diffusible.
    \n
    ⚠️ Pour obtenir les informations générales d&apos;un établissement, utiliser l&apos;API `sirene/etablissements`.
    \n
    \n
    ###### Établissements concernés&nbsp;:
    \n
    \n
    Tous les établissements des unité légales suivantes sont disponibles&nbsp;:
    \n
    * ✅ les établissements des personnes morales de droit privé (les entreprises). Toutes les entreprises immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
    \n
    * ✅ les établissements des personnes morales de droit public : les institutions et services de l&apos;État et les collectivités territoriales ;
    \n
    * ✅ les établissements des associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu&apos;elles :
    \n
    \t* emploient du personnel salarié ;
    \n
    \t* sont soumises à la TVA ;
    \n
    \t* ont demandé ou bénéficient de transferts financiers publics.
    \n
    * ✅ Les établissements des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
    \n
    \n
    Cas particulier : Les établissements de gestion de paye de la fonction publique sont bien présents dans la base Sirene mais ont été immatriculés pour les seuls besoins de certaines administrations (les impôts, les URSSAF, la DGCP …). 
    Leur diffusion à d&apos;autres administrations n&apos;est donc pas prévue.
    \n
    \n
    ###### Périmètre géographique&nbsp;:
    \n
    \n
    La base Sirene concerne les établissements implantés en métropole, dans les DOM et dans les collectivités d&apos;Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.
    \n
    \n
    ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l&apos;État ou des communes est répertorié ; ❌ les entreprises ne sont donc pas disponibles.
    \n
    \n
    ###### Fraicheur de la donnée&nbsp;:
    \n
    \n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l&apos;INSEE.<br>
    \n
    \n
    ###### Pour en savoir plus&nbsp;:
    \n
    \n
    [Contexte juridique du répertoire national d&apos;identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - etablissements_entreprises
    - etablissements_associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIRET
  parameters: &insee_unites_legales_parameters
    - Numéro de SIRET de l'établissement
  use_cases: &insee_unites_legales_use_cases
    - Aides publiques
    - Marchés publics
    - Préremplissage d'un formulaire
    - Détection de la fraude
  providers: &insee_unites_legales_providers
    - 'insee'
  faq:
    - q: "Les adresses délivrées respectent-elles la norme postale ?"
      a: "Depuis 2018, l&apos;INSEE ne fournit plus d&apos;adresse au format normé RNVP (Restructuration, Normalisation et Validation Postale), 
      nous opérons donc une reconstruction de l&apos;adresse à partir des champs disponibles dans leur nouvelle API ; 
      **cette reconstruction n&apos;est en aucun cas un traitement RNVP**, des différences minimes résultant de l&apos;arrêt du RNVP peuvent être constatées."
    - q: "Qu&apos;est-ce qu&apos;un \"non-diffusibles\" ?"
      a: "Parmi les entités présentes dans le répertoire Sirene, certaines, très majoritairement
      des personnes physiques, ont explicitement demandé de ne pas figurer en diffusion commerciale, 
      en vertu de l&apos;[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/). 
      \n
      Cela signifie qu&apos;elles donnent accord de la diffusion de leur données uniquement à des organismes habilités 
      et à des administrations. **De fait, leurs données ne sont pas publiques**.
      \n
      \n
      ℹ️ Les unités de la Défense nationale font également partie des \"non-diffusibles\" mais ne sont accessibles 
      que sur autorisation du Ministère de la Défense, conformément à l&apos;[article A123-96 du Code du Commerce](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031043097/)."
    - q: "Comment utiliser l'adresse des établissements \"non-diffusibles\" ?"
      a: "En utilisant cette API, vous vous engagez à **tenir compte du statut de diffusion le plus récent** de l&apos;entité appelée. 
      Dans le cas où l&apos;entité est indiquée comme \"non-diffusible\", vous vous engagez à n&apos;utiliser leurs informations que dans le cadre strict 
      de vos missions de service public, à ne pas les rediffuser ni les divulguer auprès de tiers non autorisés.
      \n
      \n
      {:.fr-highlight--caution}
      > ⚠️ **Vous ne pouvez pas donc pas faire usage des données d'une entité \"non-diffusible\ pour du pré-remplissage.** 
      {:.fr-highlight}
      > Il vous est par contre possible d'indiquer à l'entité \"non-diffusible\ qu&apos;elle peut modifier son statut, même provisoirement, auprès de l&apos;Insee à l&apos;adresse suivante : [https://statut-diffusion-sirene.insee.fr](https://statut-diffusion-sirene.insee.fr}{:target=\"_blank\"})."
  position: 140
  path: '/v3/insee/sirene/etablissements/diffusibles/{siret}/adresse'
  perimeter:
    description: "###### Type de données&nbsp;:
    \n
    \n
    Cette API délivre l&apos;adresse d&apos;un établissement, inscrits au répertoire Sirene et diffusibles commercialement.
    \n
    ⚠️ Elle ne concerne pas&nbsp;:
    \n
    * les établissements non-diffusibles, leur adresse est appelable avec l&apos;API `sirene/etablissements/diffusibles/{siret}/adresse` ;
    \n
    * les informations générales des établissements, appelables avec les API `/sirene/etablissements` et `/sirene/etablissements/diffusibles` ;
    \n
    \n
    ###### Établissements concernés&nbsp;:
    \n
    \n
    Les établissements des unités légales suivantes sont disponibles&nbsp;:
    \n
    * ✅ les établissements des personnes morales de droit privé (les entreprises). Toutes les entreprises immatriculées au registre du commerce et des sociétés (RCS) et au répertoire des métiers (RCM) figurent dans la base Sirene ;
    \n
    * ✅ les établissements des personnes morales de droit public : les institutions et services de l&apos;État et les collectivités territoriales ;
    \n
    * ✅ les établissements des associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu&apos;elles :
    \n
    \t* emploient du personnel salarié ;
    \n
    \t* sont soumises à la TVA ;
    \n
    \t* ont demandé ou bénéficient de transferts financiers publics.
    \n
    * ✅ Les établissements des organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
    \n
    * ❌ Les établissements des unités légales dîtes \"non-diffusibles\", c&apos;est-à-dire n&apos;ayant pas donné leur accord pour que leurs informations soient publiques et utilisées à des fins commerciales ne sont pas appelables par cette API.
    \n
    \n
    ###### Périmètre géographique&nbsp;:
    \n
    \n
    La base Sirene concerne les établissements implantés en métropole, dans les DOM et dans les collectivités d&apos;Outre-Mer de Saint-Pierre-et-Miquelon, Saint-Barthélémy et Saint-Martin.
    \n
    \n
    ⚠️ Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l&apos;État ou des communes est répertorié ; ❌ les entreprises ne sont donc pas disponibles.
    \n
    \n
    ###### Fraicheur de la donnée&nbsp;:
    \n
    \n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l&apos;INSEE.<br>
    \n
    \n
    ###### Pour en savoir plus&nbsp;:
    \n
    \n
    [Contexte juridique du répertoire national d&apos;identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - entreprises
    - associations
  opening: public
  use_cases: *insee_unites_legales_use_cases
  parameters: *insee_unites_legales_parameters
  call_id: *insee_unites_legales_call_id
  providers: *insee_unites_legales_providers
  faq:
    - q: "Les adresses délivrées respectent-elles la norme postale ?"
      a: "Depuis 2018, l&apos;INSEE ne fournit plus d&apos;adresse au format normé RNVP (Restructuration, Normalisation et Validation Postale), 
      nous opérons donc une reconstruction de l&apos;adresse à partir des champs disponibles dans leur nouvelle API ; 
      **cette reconstruction n&apos;est en aucun cas un traitement RNVP**, des différences minimes résultant de l&apos;arrêt du RNVP peuvent être constatées."
