---
- uid: 'ministere_interieur/documents_associations'
  path: '/v3/ministere_interieur/rna/associations/{siret_or_rna}/documents'
  position: 155
  perimeter:
    entity_type_description: |+
      Cette API concerne uniquement les associations.
    entities:
      - associations
  call_id: "SIRET / RNA"
  providers:
    - 'mi'
  data:
    description: |+
      Cette API indique le nombre de documents à télécharger, l’URL d’accès, le type et la date des documents.

      Les documents transmis peuvent être&nbsp;:
      - des récipissés de déclaration de création, de modification, et/ou de dissolution ;
      - les statuts de l'association ;
      - la liste des personnes habilitées à représenter l'association.

      ⚠️ Le type et le nombre de documents délivrés varient selon l'association.

  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
  use_cases_optional:
    - Détection de la fraude
  parameters:
    - Numéro de SIRET ou numéro RNA de l’association
