---
- uid: 'ministere_interieur/rna'
  path: '/v3/mi/associations/{siret_or_rna}'
  # Position au sein de l'index
  position: 150
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Informations déclarées par l&apos;association en Préfecture, entre autres&nbsp;:
    \n
    \n
    - Titre de l'association, et description courte de ses activités ; 
    \n
    - Dates de dépôt du dossier de création de l'association à la Préfecture et date de publication au Journal Officiel si elle a eu lieu ;
    \n
    - Adresse du siège social ;
    \n
    - Informations sur les dirigeants.
    \n
    \n
    **Associations concernées&nbsp;:**
    \n
    \n
    Toutes les associations inscrites au répertoire national des associations (RNA)."
    entities:
      - associations
  call_id: "SIRET / RNA"
  providers:
    - 'mi'
  opening: public
  use_cases:
    - Aides publiques
    - Marchés publics
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIRET ou numéro RNA de l’association
