---
- uid: 'inpi/actes'
  path: '/v3/inpi/unites_legales/{siren}/actes'
  position: 160
  perimeter:
    entity_type_description: "Toutes les unités légales dont les actes ont été établis après 1993 par un greffe, ce qui représente environ 25 millions d&apos;actes."
    updating_rules_description: "Théoriquement, les actes sont transmis à l&apos;INPI par le greffe dans un délai de 24h."
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  providers:
    - 'inpi'
  data:
    description: "Tous les actes établis par les greffes depuis 1993 sont transmis. Ces actes, fournis au format PDF, comportent&nbsp;:
    \n
    \n
    - des informations générales, telles que la nature de l&apos;archive, la date de dépôt en greffe, et le code greffe  ;
    \n
    - des informations sur le capital social et sa répartition ;
    \n
    - des informations sur les associés et tout ce qui est relatif à l’administration de la société.
    \n
    \n
    ℹ️ Dans le cas où un acte est manquant, si celui-ci est postérieur à 1993, l&apos;INPI peut essayer de numériser le document qui fait défaut.
Envoyez-nous votre demande détaillée en passant par le [support](https://entreprise.api.gouv.fr/support/}{:target=\"_blank\"})"
  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'unité légale.
