---
- uid: 'inpi/actes'
  path: '/v3/inpi/actes/{siren}'
  position: 160
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Tous les actes établis par les greffes depuis 1993 sont transmis par cet endpoint. 
Ce qui représente environ 25 millions d’actes. Ces actes, fournis au format PDF, comportent : 
- des informations générales ; 
- des informations sur le capital social et sa répartition ; 
- des informations sur les associés et tout ce qui est relatif à l’administration de la société.
    \n
    \n
    ℹ️ Dans le cas où un acte est manquant, l&apos;INPI peut essayer de numériser le document qui fait défaut.
    \n
    \n
    **Fraicheur de la donnée&nbsp;:**
    \n
    \n
    Théoriquement, les actes sont transmis à l’INPI par le greffe dans un délai de 24h."
    entities:
      - associations
      - entreprises
  call_id: "SIREN"
  providers:
    - 'inpi'
  opening: public
  use_cases:
    - Aides publiques
    - Marchés publics
    - Préremplissage d&apos;un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de la personne physique ou morale recherchée.
