---
- uid: 'fabrique_numerique_ministeres_sociaux/conventions_collectives'
  path: '/v3/fabrique_numerique_ministeres_sociaux/etablissements/{siret}/conventions_collectives'
  position: 170
  perimeter:
    entity_type_description: "Le périmètre est restreint aux ✅&nbsp;établissements ayant déclaré des salariés et ayant une convention, car les liens entre les établissements et les conventions collectives sont issues de la déclaration sociale nominative (DSN).
    \n
    ❌ Les sociétés unipersonnelles dont le gérant est assimilé salarié ne sont pas concernées par cette API, même si la société en question est rattachée à une convention collective."
    updating_rules_description: "⚠️ La fréquence de mise à jour du fichier fourni par la DARES (une des deux sources de cette API) n&apos;est pas précisée."
    entities:
      - associations
      - entreprises
  call_id: "SIRET"
  providers:
    - 'fabsocial'
  data:
    description: "Cette API délivre la liste des différentes conventions de l&apos;établissement.
Les caractéristiques suivantes sont transmises&nbsp;:
    \n
    \n
    - le titre, long et court de la convention ;
    \n
    - l&apos;état de la convention, étendu ou non, c'est-à-dire si la convention est applicable à tous les employeurs de la branche ou uniquement aux signataires ;
    \n
    - l&apos;identifiant IDCC, numéro à 4 chiffres ;
    \n
    - l&apos;URL Légifrance du texte en vigueur."
  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
  parameters:
    - Numéro de SIRET de l&apos;établissement
  faq:
    - q: "Quelles sont les sources de données de cette API ?"
      a: "Cette API est fournie par la fabrique numérique des ministères sociaux qui s&apos;appuie sur plusieurs sources de données&nbsp;:
      \n
      \n
      - les données d&apos;affiliation des établissements d&apos;entreprise aux conventions sont **issues de la [DARES](https://dares.travail-emploi.gouv.fr/}{:target=\"_blank\"})**,
direction d&apos;études et statistiques du Ministère du Travail, publiées sur sur [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/liste-des-conventions-collectives-par-entreprise-siret/}{:target=\"_blank\"}) ;
      \n
      - Les informations relatives aux conventions collectives (numéro identifiant, titre, lien vers le texte légal, …)
sont issues de la base [KALI](https://www.data.gouv.fr/fr/datasets/kali-conventions-collectives-nationales/}{:target=\"_blank\"}) **diffusée par la [DILA](https://www.dila.premier-ministre.gouv.fr/}{:target=\"_blank\"})**, direction de l’information légale et administrative.
      \n
      \n
      ⚠️ La fréquence de mise à jour du fichier fournie par la DARES n’est pas précisée."
