---
- uid: 'cma_france/rnm'
  path: '/v3/rnm/entreprises/{siren}'
  position: 180
  perimeter:
    description: "###### Type de données&nbsp;:
    \n
    \n
    Cette API délivre des informations de référence sur les entreprises artisanales, données fournies par la Chambre des Métiers et de l&apos;Artisanat France (CMA France), telles que&nbsp;:
    \n
    \n
    - des informations générales et juridiques, telles que le nom de l&apos;entreprise, s&apos;il s&apos;agit personne physique ou morale, sa forme juridique, son effectif et l&apos;origine du fond de commerce ;
    \n
    - des données définissant le type d&apos;activité de l&apos;entreprise, telles que le code NAFA, le secteur d&apos;activité (NAR), et l&apos;indication si l&apos;activité est permanente ou saisonnière et/ou ambulante ;
    \n
    - des informations géographiques, notamment l&apos;adresse ;
    \n
    - des informations sur les dirigeants ;
    \n
    - les dates clés (immatriculation, radiation, début d&apos;activité …) ainsi que le code du centre de formalité des entreprises (CFE) ;
    \n
    - des informations en cas de double immatriculation ;
    \n
    - des informations spécifiques au RNM (identifiants, dates d&apos;import et date de mise à jour des données) ;
    \n
    \n
    Ces données sont également disponibles en [API publique et libre d&apos;accès sur api.gouv.fr](https://api.gouv.fr/les-api/api_rnm}{:target=\"_blank\"}).
    \n
    \n
    ###### Entreprises concernées&nbsp;:
    \n
    \n
    Cette API couvre toutes les entreprises enregistrées au répertoire national des métiers (RNM).
    \n
    \n
    Sont obligatoirement immatriculées au répertoire des métiers&nbsp;:
    \n
    \n
    - ✅ les entreprises individuelles et les sociétés qui n&apos;emploient pas plus de dix salariés et exercent à titre principal ou secondaire une activité artisanale de production, de transformation, de réparation ou de prestation de service figurant en [annexe du décret du 2 avril 1998](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000021964896/2009-02-02/}{:target=\"_blank\"}).
    \n
    - ✅ Les personnes qui exercent l&apos;activité de fabrication de plats à consommer sur place peuvent également être immatriculées au répertoire des métiers.
    \n
    \n
    Peuvent être immatriculées au RNM&nbsp;:
    \n
    \n
    - ✅ les entreprises qui dépassent le seuil de dix salariés si leur dirigeant peut se prévaloir de la qualité d&apos;artisan, d&apos;artisan d&apos;art ou de maitre artisan.
    \n
    \n
    ###### Fraicheur de la donnée&nbsp;:
    \n
    \n
    La fraîcheur des données de cette API correspond à la date de mise à jour faite du répertoire RNM 
suite aux nouvelles informations déclarées par l&apos;entrepreneur. Cette date est indiquée dans l&apos;API par la clé `rnm_date_mise_a_jour`. 
Dans le cas où il n&apos;y a pas encore eu de changement répertorié, la date d&apos;import `rnm_date_import` fait alors référence.
    \n
    \n
    {:.fr-highlight--caution}
    > ⚠️ Cependant, les dates ci-dessus ne garantissent pas la fraicheur de toutes les données renvoyées, car leur mise à jour n&apos;est pas obligatoire.
    > Les données d&apos;effectifs `effectif_salarie` et `effectif_apprenti` sont notamment à prendre avec vigilance car elles peuvent dater de la première déclaration.
    \n
    \n
    **Liste des évènements qui doivent être obligatoirement déclarés&nbsp;:**
    \n
    \n
    - changement d&apos;adresse ;
    \n
    - changement de nom commercial ;
    \n
    - changement d&apos;enseigne ;
    \n
    - modification d&apos;activité(s) de l&apos;entreprise ;
    \n
    - mise en location gérance, mention de conjoint collaborateur ;
    \n
    - ouverture ou fermeture d&apos;un établissement ;
    \n
    - changement de la forme juridique ;
    \n
    - changement de dirigeant ;
    \n
    - dissolution de la société ;
    \n
    - cessation temporaire ou totale d&apos;activité ;
    \n
    - régularisation d&apos;immatriculation pour les micro-entrepreneurs.
    \n
    \n
    Il est à noter que **l&apos;entrepreneur n&apos;a pas d&apos;obligation légale à déclarer un changement d&apos;effectif**.
De fait, l&apos;actualisation de cette donnée dépend donc du bon vouloir de l&apos;entrepreneur à revérifier tous les champs du formulaire
au moment de sa déclaration d&apos;un événement dit obligatoire. Néanmoins, **généralement**, étant donné que toute modification du répertoire implique des coûts, **l&apos;entreprise met à jour l&apos;ensemble de ses données**."
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'cma'
  opening: public
  use_cases:
    - Marchés publics
    - Aides publiques
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:
    - q: "Qu&apos;est ce que les codes NAFA, NAR 4 et NAR 20 ?"
      a: "###### Le code NAFA
      \n
      \n
      Le code NAFA est un identifiant permettant de naviguer dans la Nomenclature d&apos;Activités Françaises de l&apos;Artisanat qui décrit les activités artisanales.
Il est composé de six caractères, quatre chiffres et deux lettres.
Les cinq premiers caractères sont ceux de l&apos;Activité Principale de l&apos;Entreprise (APE)
et correspondent au code NAF. La lettre située en sixième position permet de préciser le contenu du poste NAFA par rapport à la classe NAF.
      \n
      \n
      **Pour en savoir plus :**
      \n
      \n
      - La [page dédiée du Ministère de l&apos;économie, des finances et de la relance](https://www.entreprises.gouv.fr/fr/commerce-et-artisanat/la-nomenclature-d-activites-francaise-de-l-artisanat}{:target=\"_blank\"}) détaille les règles ayant défini cette nomenclature. Vous y trouverez également plus d&apos;informations sur le lien entre code NAF et NAFA.<br />
      \n
      - CMA France propose un [registre de la nomenclature](http://nafa.apcma.fr/jlbweb/jlbWeb?html=NAFA/accueil}{:target=\"_blank\"}), qui donne un descriptif précis de chaque activité.
      \n
      \n
      ###### Les codes NAR 4 et 20
      \n
      \n
      Les codes NAR sont issus des Nomenclatures Artisanales Regroupées. Ils permettent de connaître le secteur d&apos;activité de l&apos;entreprise artisanale.
      \n
      Le numéro associé correspond au degré de précision en nombre de secteurs.
      La NAR 4 comprend quatre secteurs d&apos;activités, qui regroupent les vingt secteurs plus précis de la NAR 20.
      \n
      \n
      **Pour en savoir plus :**
      \n
      \n
      - Le site de CMA France tient un [registre de tous les codes NAFA](http://nafa.apcma.fr/jlbweb/jlbWeb?html=NAFA/accueil}{:target=\"_blank\"}), accompagné des codes NAR 4 et 20, et même des code NAR 8 et 80.
      \n
      - Une [liste (non-officielle)](https://entreprise.api.gouv.fr/assets/pdf/liste-nar.pdf}{:target=\"_blank\"}) est consultable."
    - q: "Quelles sont les différents types de déclarations renvoyées ?"
      a: "La clé `declaration_procedures` permet d&apos;obtenir différents types de déclarations&nbsp;:
      \n
      \n
      - les déclarations de **cessation des paiements** et les décisions intervenues dans les **procédures de règlement judiciaire et de liquidation des biens** en application de la [loi n° 67-563 du 13 juillet 1967](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006398426/1980-05-13/}{:target=\"_blank\"}) ;
      \n
      - les déclarations intervenues dans les procédures ouvertes en application de l&apos;ordonnance n° 67-820 du 23 septembre 1967 tendant à faciliter le **redressement économique et financier** ;
      \n
      - les déclarations de **cessation des paiements** et les décisions suivantes intervenues dans les procédures de **redressement** ou de **liquidation judiciaires** des entreprises ouvertes avant le 1er janvier 2006 en application du code de commerce ;
      \n
      - les déclarations intervenues dans les procédures de **sauvegarde**, de **redressement judiciaire** ou de **liquidation judiciaire** ouvertes à compter du 1er janvier 2006.
      \n
      \n"
    - q: "Quelle est la distinciton entre un nom de naissance, d&apos;usage ou un pseudonyme ?"
      a: "Cette API délivre plusieurs types de noms et prénoms du dirigeant.
      \n
      \n
      ##### Le nom de naissance
      \n
      \n
      La clé `dirigeant_nom_de_naissance` délivre le nom de famille **donné à la personne le jour de la déclaration de sa naissance**.
      Ce peut être :
      \n
      \n
      - soit le nom du père, 
      \n
      - soit le nom de la mère,
      \n
      - soit leurs deux noms accolés dans l&apos;ordre choisi par eux dans la limite d&apos;un nom de famille pour chacun d&apos;eux (Article 311-21 du code civil). 
      \n
      \n
      Le nom de naissance est aussi le nom qui figure au registre de l&apos;état civil. Cette législation est récente et a pris effet au 1er septembre 2003.
      ⚠️ Ce nom **peut être différent du nom de famille** (qui n&apos;est pas donné par l&apos;API) dans le cas où la personne a demandé un changement de nom.
      \n
      \n
      ##### Le nom d&apos;usage
      \n
      \n
      La clé `dirigeant_nom_usage` indique le nom que la personne a **choisi d&apos;utiliser dans la vie quotidienne**.
      Toutefois, ne sont autorisées que **trois formes de noms d&apos;usage**&nbsp;:
      \n
      \n
      - un double nom composé du nom de famille de la personne et du nom du parent qui n&apos;a pas transmis son nom à la naissance.
      \n
      - un double nom composé du nom de famille de la personne et du nom de la personne avec qui elle est mariée.
      \n
      - le nom de la personne avec qui la personne est mariée, ce nom peut alors aussi être dénommé \"nom marital\".
      \n
      \n
      Le nom d&apos;usage **ne figure ni à l&apos;état civil ni sur le livret de famille** ; il peut figurer sur la carte d&apos;identité ou le passeport. Les administrations se doivent de l&apos;utiliser si cela est demandé par la personne.
      \n
      \n
      ##### Le pseudonyme
      \n
      \n
      La clé `dirigeant_pseudonyme` indique le **nom d&apos;emprunt utilisé par le dirigeant pour se désigner dans l&apos;exercice de son activité**, généralement littéraire ou artistique. 
      \n
      \n
      Le pseudonyme ne correspond pas à un changement de nom, et son choix doit remplir certaines conditions. Il ne doit pas porter atteinte à l&apos;ordre public et il ne doit pas permettre à la personne de s&apos;approprier la renommée ou la parenté d&apos;une personne tiers.
      Le pseudonyme peut être protégé en étant déposé sous la forme d&apos;une marque à l&apos;INPI."

