---
- uid: 'cma_france/rnm'
  path: '/v3/rnm/entreprises/{siren}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Cette API délivre des informations de référence fournies par la Chambre des Métiers et de l’Artisanat France (CMA France)
 concernant les entreprises artisanales telles que&nbsp;:
    \n
    \n
    - des informations générales et juridiques (nom de l’entreprise, personne physique/morale, forme juridique, effectif, l’origine du fond de commerce, activité permanente/saisonnière, activité ambulante, code du centre de formalité des entreprises (CFE) ayant fait l’inscription et les déclarations, s’il y en a, relatives à un redressement judiciaire ou une liquidation.)
    \n   
    - le type d’activité de l’entreprise (code NAFA et secteur d’activité (NAR)) ;
    \n
    - des informations géographiques, notamment l’adresse ;
    \n
    - des informations sur les dirigeants ;
    \n   
    - les dates clés (immatriculation, radiation, début d’activité …)
    \n    
    - des informations en cas de double immatriculation ;
    \n    
    - des informations spécifiques au RNM (identifiants, dates d’import et date de mise à jour des données) ;
    \n
    \n
    Ces données sont également disponibles en [API publique et libre d’accès sur api.gouv.fr](https://api.gouv.fr/les-api/api_rnm}{:target="_blank"}).
    \n
    \n
    **Entreprises concernées&nbsp;:**
    \n
    \n
    Cette API couvre toutes les entreprises enregistrées au répertoire national des métiers (RNM).
    \n
    \n
    Sont obligatoirement immatriculées au répertoire des métiers&nbsp;:
    \n
    \n
    - ✅ les entreprises individuelles et les sociétés qui n’emploient pas plus de dix salariés et exercent à titre principal ou secondaire une activité artisanale de production, de transformation, de réparation ou de prestation de service figurant en annexe du décret du 2 avril 1998.
    \n
    - ✅ Les personnes qui exercent l’activité de fabrication de plats à consommer sur place peuvent également être immatriculées au répertoire des métiers.
    \n
    \n
    Peuvent être immatriculées au RNM&nbsp;:
    \n
    \n
    - ✅ les entreprises qui dépassent le seuil de dix salariés si leur dirigeant peut se prévaloir de la qualité d’artisan, d’artisan d’art ou de maitre artisan.
    \n
    \n
    **Fraicheur de la donnée&nbsp;:**
    \n
    \n
    "
    entities:
      - entreprises
  call_id: "SIREN"
  providers:
    - 'cma'
  opening: public
  use_cases:
    - Aides publiques
    - Marchés publics
    - Préremplissage d'un formulaire
    - Détection de la fraude
  parameters:
    - Numéro de SIREN de l'entreprise
  faq:  
    - q: "Quelles sont les sources des données de conventions collectives de de cette API ?"
      a: "\n
      \n
      ##### Du côté de l'entreprise
      \n
      \n
      Parmi les événements qui surviennent dans la vie d'une entreprise artisanale, 
certains d'entre eux doivent être obligatoirement déclarés par l'entreprise à sa chambre de commerce et d'artisanat, 
c'est à dire son centre de formalité des entreprises.
      **Généralement**, étant donné que toute modification du répertoire implique des coûts, 
**l'entreprise met à jour l'ensemble de ses données**.
      \n
      \n
      Voici la liste des évènements qui impliquent obligatoirement une déclaration : 
      \n
      \n
      - Changement d’adresse ;
      \n
      - changement de nom commercial ;
      \n
      - changement d’enseigne ;
      \n
      - modification d’activité(s) de l’entreprise ;
      \n
      - mise en location gérance, mention de conjoint collaborateur ;
      \n
      - ouverture ou fermeture d’un établissement ;
      \n
      - changement de la forme juridique ; 
      \n
      - changement de dirigeant ;
      \n
      - dissolution de la société ;
      \n
      - cessation temporaire ou totale d’activité ;
      \n
      - régularisation d'immatriculation pour les micro-entrepreneurs.
      \n
      \n
      Il est à noter que **l'entrepreneur n'a pas d'obligation légale à déclarer un changement d'effectif**. 
De fait, l'actualisation de cette donnée dépend donc du bon vouloir de l'entrepreneur à revérifier tous les champs du formulaire 
au moment de sa déclaration d'un événement dit obligatoire.
      \n
      \n
      ##### Du côté de la réponse JSON
      \n
      \n
      La fraîcheur des données communiquées par cette API correspond à la date de mise à jour faite dans le RNM 
suite aux nouvelles informations déclarées par l'entrepreneur. Cette date est indiquée par la clé `rnm_date_mise_a_jour` dans la réponse JSON.
      Dans le cas où il n'y a pas encore eu de changement répertorié, la date d'import `rnm_date_import` fait alors référence.
      \n
      \n
      ⚠️ La fraicheur des données d'effectifs `effectif_salarie` et `effectif_apprenti` est à 
prendre avec vigilance puisque leur mise à jour n'est pas obligatoire."
    - q: "Qu'est ce que les codes NAFA, NAR 4 et NAR 20 ?"
      a: "
      ###### Le code NAFA
      \n
      \n
      Le code NAFA est un identifiant permettant de naviguer dans la Nomenclature d'Activités Françaises de l'Artisanat qui décrit les activités artisanales. 
Il est composé de six caractères, quatre chiffres et deux lettres. 
Les cinq premiers caractères sont ceux de l'Activité Principale de l'Entreprise (APE) 
et correspondent au code NAF. La lettre située en sixième position permet de préciser le contenu du poste NAFA par rapport à la classe NAF.
      \n
      \n
      **Pour en savoir plus :**
      \n
      \n
      La [page dédiée du Ministère de l'économie, des finances et de la relance](https://www.entreprises.gouv.fr/fr/commerce-et-artisanat/la-nomenclature-d-activites-francaise-de-l-artisanat}{:target="_blank"}) détaille les lois ayant défini cette nomenclature. Vous y trouverez également plus d'informations sur le lien entre code NAF et NAFA.<br />
      CMA France propose un [registre de la nomenclature](http://nafa.apcma.fr/jlbweb/jlbWeb?html=NAFA/accueil}{:target="_blank"}), qui donne un descriptif précis de chaque activité.
      \n
      \n
      ###### Les codes NAR 4 et 20
      \n
      \n
      Les codes NAR sont issus des Nomenclatures Artisanales Regroupées. Ils permettent de connaître le secteur d'activité de l'entreprise artisanale.
      \n
      Le numéro associé correspond au degré de précision en nombre de secteurs.
      La NAR 4 comprend quatre secteurs d'activités, qui regroupent les vingt secteurs plus précis de la NAR 20.
      \n
      \n
      **Pour en savoir plus :**
      \n
      \n
      - Le site de CMA France tient un [registre de tous les codes NAFA](http://nafa.apcma.fr/jlbweb/jlbWeb?html=NAFA/accueil}{:target="_blank"}), accompagné des codes NAR 4 et 20, et même des code NAR 8 et 80.
      \n
      - Une [liste (non-officielle)](https://entreprise.api.gouv.fr/assets/pdf/liste-nar.pdf}{:target="_blank"}) est consultable."
    - q: "Quelles sont les différents types de déclarations renvoyées ?"
      a: "La clé `declaration_procedures` permet d'obtenir différents types de déclarations&nbsp;:
      \n
      \n
      - les déclarations de **cessation des paiements** et les décisions intervenues dans les **procédures de règlement judiciaire et de liquidation des biens** en application de la [loi n° 67-563 du 13 juillet 1967](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006398426/1980-05-13/}{:target="_blank"}) ;
      \n
      - les déclarations intervenues dans les procédures ouvertes en application de l'ordonnance n° 67-820 du 23 septembre 1967 tendant à faciliter le **redressement économique et financier** ;
      \n
      - les déclarations de **cessation des paiements** et les décisions suivantes intervenues dans les procédures de **redressement** ou de **liquidation judiciaires** des entreprises ouvertes avant le 1er janvier 2006 en application du code de commerce ;
      \n
      - les déclarations intervenues dans les procédures de **sauvegarde**, de **redressement judiciaire** ou de **liquidation judiciaire** ouvertes à compter du 1er janvier 2006.
      \n
      \n"
    - q: "Quelle est la distinciton entre un nom de naissance, d'usage ou un pseudonyme ?"
      a: "La réponse JSON vous délivre plusieurs types de noms et prénoms du dirigeant. 
      \n
      \n
      ##### Le nom de naissance
      \n
      \n
      La clé `dirigeant_nom_de_naissance` délivre le nom de famille **donné à la personne le jour de la déclaration de sa naissance**.
      Ce peut être soit le nom du père, soit le nom de la mère, soit leurs deux noms accolés dans l'ordre choisi par eux dans la limite d'un nom de famille pour chacun d'eux (Article 311-21 du code civil). C'est aussi le nom qui figure au registre de l'état civil. Cette législation est récente et a pris effet au 1er septembre 2003.
      Ce nom **peut être différent du nom de famille** (qui n'est pas donné par l'API) dans le cas où la personne à demander un changement de nom.
      \n
      \n
      ##### Le nom d'usage
      \n
      \n
      La clé `dirigeant_nom_usage` indique le nom que la personne a **choisi d'utiliser dans la vie quotidienne**.
      Toutefois, ne sont autorisées que **trois formes de noms d'usage**&nbsp;:
      \n
      \n
      - un double nom composé du nom de famille de la personne et du nom du parent qui n'a pas transmis son nom à la naissance.
      \n
      - un double nom composé du nom de famille de la personne et du nom de la personne avec qui elle est mariée.
      \n
      - le nom de la personne avec qui la personne est mariée, ce nom peut alors aussi être dénommé "nom marital".
      \n
      \n
      Le nom d'usage **ne figure ni à l'état civil ni sur le livret de famille** ; il peut figurer sur la carte d'identité ou le passeport. Les administrations se doivent de l'utiliser si cela est demandé par la personne.
      \n
      \n
      ##### Le pseudonyme
      \n
      \n
      La clé `dirigeant_pseudonyme` indique le **nom d'emprunt utilisé dans l'exercice de son activité** par le dirigeant pour se désigner, généralement littéraire ou artistique. Le pseudonyme ne correspond pas à un changement de nom, et son choix doit remplir certaines conditions. Il ne doit pas porter atteinte à l'ordre public et il ne doit pas permettre à la personne de s'approprier la renommée ou la parenté d'une personne tiers.
      Le pseudonyme peut être protégé en étant déposé sous la forme d'une marque à l'INPI."

