---
- uid: 'douanes/immatriculation_eori'
  path: '/v3/dgddi/eoris/{siret_or_eori}'
  position: 140
  perimeter:
    description: "**Type de données&nbsp;:**
    \n
    \n
    Cette API délivre le statut **actif ou non du numéro EORI** de l'entreprise. 
Si le numéro EORI n'est plus actif, cela signifie que l'entreprise n'est plus autorisée à importer ou exporter en Union Européenne.
    \n
    \n
    La raison sociale et l'adresse de l'entreprise telles qu'enregistrée auprès des douanes sont aussi précisées.
    \n
    \n
    **Établissements concernés&nbsp;:**
    \n
    \n
    L'API `/numero_eori` couvre ✅ **toutes les entreprises faisant des
    échanges commerciaux** entrant et sortant au sein de l'Union européenne.
    Le périmètre des entreprises trouvables est cependant différent selon si l'appel est effectué avec le numéro EORI ou le SIRET de l'entreprise&nbps;:
    \n
    \n
    ##### Appel avec un numéro EORI&nbps;:
    \n
    \n
    À condition de connaître le numéro EORI de l'entreprise recherchée, vous pouvez accéder au statut de l'immatriculation de ✅ toutes les entreprises de la base des douanes.
    \n
    \n
    ##### Appel avec un numéro de SIRET&bsp;::
    \n
    \n
    - Pour les ✅ entreprises ayant réalisé leur immatriculation EORI en France, vous pouvez utiliser le numéro de SIRET comme paramètre d'appel.
    \n
    - Pour les ❌ entreprises françaises ayant été fait leur immatriculation EORI dans un autre pays européen ; l'appel par SIRET ne fonctionne pas, et vous renverra toujours un négatif, même si l'entreprise possède un numéro EORI actif.
    \n
    \n
    ℹ️ Plus d'informations sur le site des [douanes](https://www.douane.gouv.fr/fiche/numero-eori-economic-operator-registration-and-identification}{:target="_blank"}) ou sur le site de l'[Union Européenne](https://ec.europa.eu/taxation_customs/business/customs-procedures/general-overview/economic-operators-registration-identification-number-eori_fr}{:target="_blank"}).
    \n
    \n"
    entities:
      - entreprises
  call_id: "Numéro EORI / SIRET"
  providers:
    - 'douanes
  opening: public
  use_cases:
    - Aides publiques
    - Marchés publics
    - Détection de la fraude
  parameters:
    - Numéro EORI de l'entreprise ou son SIRET si elle est immatriculée en France
  faq:  
    - q: "À quoi ressemble un numéro EORI ?"
      a: "Pour les entreprises françaises ayant fait leur demande de numéro EORI auprès des douanes française celui-ci est FR+SIRET (par exemple : FR16002307300010).
      \n
      \n
      Sinon le numéro est composé de deux lettres du pays émetteur suivi d’un code ou d’un numéro unique dans cet État membre (par exemple : ES12345678)."
    - q: "Je ne connais pas le numéro EORI de l'entreprise"
      a: "Vous pouvez appeler cette API avec le SIRET de l’entreprise, si celle-ci a effectuée sa demande d’attribution de numéro EORI en France nous la trouverons.
      \n
      \n
      Cependant si cette entreprise a fait sa demande d’attribution de numéro EORI dans un autre pays membre de l’Union Européenne, il vous faudra demander ce numéro directement à l’entreprise. Il n’existe aucun moyen de trouver ce numéro.
      \n
      \n
      ⚠️ Si vous ne savez pas si l’entreprise française a effectué son immatriculation en France, une réponse négative de l’endpoint peut être un faux négatif."
