---
- uid: 'insee/unites_legales'
  path: '/v3/insee/sirene/unites_legales/{siren}'
  perimeter:
    description: &insee_unites_legales_perimeter_description "Ce endpoint vous donne accès :
\n
    * aux données tirées du *Répertoire National d'identification des entreprises et des établissements*, géré par l'INSEE au travers du système Sirene ;
\n
    * ainsi qu'aux observations d'Infogreffe, quand elles sont disponibles pour le SIREN appelé.
\n
\n
    ⚠️ Cet endpoint ne concerne pas les établissements, ceux-ci sont appelables avec l'endpoint `etablissement_insee`.
\n
\n
    **Cet endpoint permet donc d'accéder aux informations de référence concernant :**
\n
\n
    * ✅ les personnes morales de droit privé : les entreprises.
\n
    * ℹ️ Toutes les entreprises immatriculées au Registre du Commerce et des Sociétés et au Répertoire des Métiers figurent dans la base Sirene ;
\n
    * ✅ les personnes morales de droit public : les institutions et services de l’État et les collectivités territoriales ;
\n
    * ✅ les entrepreneurs individuels exerçant de manière indépendante une profession non salariée (exemple : un commerçant, un médecin), ayant fait une déclaration d'activité.
\n
    * ❌ Les particuliers employeurs ne font pas partie de la base Sirene ;
\n
    * ✅ les associations ayant, en plus de leur numéro RNA, un numéro de SIREN/SIRET délivré lorsqu'elles :
\n
    \t* emploient du personnel salarié ;
\n
    \t* sont soumises à la TVA ;
\n
    \t* ont demandé ou bénéficient de transferts financiers publics.
\n
    * ✅ Les organismes publics ou privés et les entreprises étrangères qui ont une représentation ou une activité en France.
\n
\n
    **Périmètre géographique :**
\n
\n
    La base Sirene concerne les unités implantées en métropole, dans les DOM et dans les collectivités d'Outre-Mer de Saint Pierre et Miquelon, Saint Barthélémy et Saint Martin.
\n
\n
* ⚠️  Pour la Nouvelle-Calédonie, la Polynésie française, et Wallis-et-Futuna, seul le secteur public administratif, de l'État ou des communes est répertorié
\n
* ❌ les entreprises ne sont donc pas disponibles.
\n
\n
    **Fraicheur de la donnée :**
\n
\n
    La mise a jour des données est faite quotidiennement entre 0h et 3h à l'INSEE.<br>
\n
\n
    **Pour en savoir plus :**
\n
\n
    [Contexte juridique du Répertoire National d’identification des entreprises et des établissements](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=134EFA0EE7BDCA89C2D6B31E02C48430.tplgfr30s_3?idSectionTA=LEGISCTA000006178890&cidTexte=LEGITEXT000005634379&dateTexte=20100904)"
    entities:
    - entreprises_diffusibles
    - associations
  opening: protected
  call_id: &insee_unites_legales_call_id SIREN
  providers: &insee_unites_legales_providers
    - 'insee'

- uid: 'insee/unites_legales_diffusibles'
  path: '/v3/insee/sirene/unites_legales/diffusibles/{siren}'
  perimeter:
    description: *insee_unites_legales_perimeter_description
    entities:
    - entreprises
    - associations
  opening: public
  call_id: *insee_unites_legales_call_id
  providers: *insee_unites_legales_providers

