---
- uid: 'urssaf/attestation_sociale'
  path: '/v3/acoss/attestations_sociales/{siren}'
  perimeter:
    summary: "Toutes les entreprises sont concernées."
    description: ""
  opening: "Données protégées"
  providers:
    - 'acoss'
