en:
  errors:
    password_confirmation: must be equal to password

    rules:
      password:
        format?: 'minimum eight characters, at least one uppercase letter, one lowercase letter and one number'

    cgu_checked: 'CGU must be accepted'

    unique?: 'value already exists'

    confirmation_token_exists?: 'confirmation token not found'
    confirmation_token_used?: 'user already confirmed'

    role_exists?: 'role "%{code}" does not exist'

    user_exists?: 'user with ID "%{uid}" does not exist'
    email_exists?: 'user with email "%{email}" does not exist'

    pwd_token_exists?: 'Le lien de régénération de mot de passe est invalide'
