development:
  jwt_expiration_notice:
    cron: '0 1 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

sandbox:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

  jwt_satisfaction_survey:
    # every day at 3:00 a.m.
    cron: '0 3 * * *'
    class: 'AccessRequestSatisfactionSurveyJob'
    queue: default

staging:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

  jwt_satisfaction_survey:
    cron: '0 3 * * *'
    class: 'AccessRequestSatisfactionSurveyJob'
    queue: default

production:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'JwtApiEntrepriseExpirationNoticeJob'
    queue: default

  jwt_purge:
    cron: '0 2 * * 6'
    class: 'JwtApiEntreprisePurgeJob'
    queue: default

  jwt_satisfaction_survey:
    cron: '0 3 * * *'
    class: 'AccessRequestSatisfactionSurveyJob'
    queue: default
