development:
  jwt_expiration_notice:
    cron: '0 1 * * *'
    class: 'TokenExpirationNoticeJob'
    queue: default

sandbox:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'TokenExpirationNoticeJob'
    queue: default

production:
  jwt_expiration_notice:
    cron: '0 */4 * * *'
    class: 'TokenExpirationNoticeJob'
    queue: default
